# Generated by Django 4.1.7 on 2023-05-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=60)),
                ('Last_Name', models.CharField(max_length=60)),
                ('Mobile', models.CharField(max_length=60)),
                ('Email', models.CharField(max_length=60)),
                ('Password', models.CharField(max_length=60)),
                ('DOB', models.DateField()),
            ],
        ),
    ]
