# Generated by Django 4.1.7 on 2023-05-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_Type', models.CharField(max_length=60)),
                ('AC_NON_AC', models.CharField(max_length=60)),
                ('Mobile', models.CharField(max_length=60)),
                ('Email', models.CharField(max_length=60)),
                ('Password', models.CharField(max_length=60)),
                ('DOB', models.DateField()),
            ],
        ),
    ]
